# Generated by Django 4.2.6 on 2023-10-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_rename_created_at_facebookpost_created_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facebookpost",
            name="created_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
